---

name: latest
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  latest:
    name: "latest"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
