---

name: linting
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linting:
    name: "linting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .
