---

name: pr
on:
  push:
    branches-ignore:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  pr:
    name: "pr"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
