---

name: release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
